---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

# my-docker:
 #  host: 10.0.0.243
#   port: 2375

 #my-docker:
#   socket: /var/run/docker.sock
