---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: My custom Homepage
background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  #image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-m>
  blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100

language: fr 
useEqualHeights: true
showStats: true




layout:
  Containers:
    tab: Services
  Hypervisor:
    tab: Services
  DNS:
    tab: utilities
  Media:
    tab: Media Management
  downloads:
    tab: Media Management
